### ISSUE TITLE
PulseTile Token older than token on qewd server?

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/PulseTile-React#14]
![image](https://user-images.githubusercontent.com/939996/41151753-983c870e-6b09-11e8-9d4d-a7bf87e3291d.png)

JWT issue, as discussed with Bogdan,
PulseTile needs to redirect to login page

**Comment by PhilBarrett** [comment]
Duplication of 
https://github.com/PulseTile/PulseTile-React-Core/issues/186 and
https://github.com/PulseTile/PulseTile-React-Core/issues/159
