### ISSUE TITLE
Roboto Font Weights

### ISSUE THREAD

**Issue by simongamester** [LeedsCC/PulseTile-React#2]
Hi,

I've just noticed that the font weights used on the label.control-label elements don't appear to be rendering in bold. These currently have a weight of 700, but look no different the 400 weighted fonts in the text below. I'm assuming the Roboto font is not pulling in all the font weights used in the CSS?

Thanks,

Simon

**Comment by tony-shannon** [comment]
Will close this @simongamester  as no recent updates
Please feel free to reopen if needs be
