### ISSUE TITLE
Helm - Customise cog behaviour has changed

### ISSUE THREAD

**Issue by PhilBarrett** [LeedsCC/PulseTile-React#22]
Until recently the user when clicking on the cog on the summary screen, could make the following customisations:
1. View just the summary text for each of the tiles (e.g. first 4 problems/contact/medications etc)
2. View just the image for each of the tiles (e.g. problems, contacts, medications)
3. View both the image and the summary text for each of the tiles. 

These options have recently been removed and need reinstating. 

![screen shot 2018-08-07 at 09 44 20](https://user-images.githubusercontent.com/12699244/43765052-ed1de8c0-9a26-11e8-94d2-6cc58ace70b2.png)

**Comment by kuvakina** [comment]
@PhilBarrett 

Sorry, we found the problem. Already solved it.

**Comment by PhilBarrett** [comment]
Tested and back working as intended, thanks @kuvakina
