### ISSUE TITLE
issue with URL leedsphr version while using domain

### ISSUE THREAD

**Issue by anna-otrokhova** [LeedsCC/PulseTile-React#3]
Recently we have noticed that by using this link http://leedsphr.ripple.foundation/ and walking through the site the URL ether isn't changed or has the wrong path.
Please compare:
http://46.101.50.79/#/patients?department=Neighbourhood
http://prntscr.com/ifigr3 
and here:
http://prntscr.com/ifijlu

Eventually, when the user reloads the chart page they are redirected to a Patient Summary page.
And when user reloads a page with tables, it is blank and has wrong url: http://prntscr.com/ifikgb

This issue doesn't exist when the URLs are correct because the rendering of the view components depends on the URL. http://prntscr.com/ifijlu

**Comment by tony-shannon** [comment]
the config and set up of these instances has changed , so am closing this issue for now
