### ISSUE TITLE
leeds phr issue with Logo on mgateway box

### ISSUE THREAD

**Issue by anna-otrokhova** [LeedsCC/PulseTile-React#4]
I found an issue with logo on this machine http://www.mgateway.com:8080/#/patients/9999999000/patients-summary
http://prntscr.com/ifiufz

This issue isn't faced on this leedsphr box which we have been working on:  http://prntscr.com/ifivw8

We suppose the issue is here: 
our version http://joxi.ru/a2XageaF1GzGQA
mgateway version: http://joxi.ru/l2ZnGVnswx5on2

**Comment by anna-otrokhova** [comment]
@tony-shannon 
Can I ask Rob to check it?

**Comment by tony-shannon** [comment]
Yes Anna, please do
The LeedsPHR demo shouldnt need to be on the mgateway box anyway.
that was a short term fix I think
thanks
T
