### ISSUE TITLE
Helm PHR- May2017 demo/prep- tidyup issues

### ISSUE THREAD

**Issue by tony-shannon** [LeedsCC/PulseTile-React#5]
To Do

**Comment by tony-shannon** [comment]
[ ] UI Resource bundling - check if ok?

**Comment by robtweed** [comment]
Regarding the last point - UI bundling - the latest build seems to not be bundling all the JS resources into a single main.js file.  Instead we now have lots of additional JS files (eg vitals.js, vaccinations.js etc)

The UI appears to still run OK, but previously all the UI JS files were bundled into one file.  Why has this changed?

**Comment by robtweed** [comment]
Leeds PHR / Helm PulseTile UI development should now invoke the middle tier APIs on http://dev.ripple.foundation:8000

**Comment by tony-shannon** [comment]
See this feeds preview
![image](https://user-images.githubusercontent.com/939996/39880954-2aaae558-5477-11e8-8906-2ca69819ec3f.png)

**Comment by tony-shannon** [comment]
See this re image mismatch
![image](https://user-images.githubusercontent.com/939996/39881296-6813beaa-5478-11e8-9d39-c1aa5264e311.png)

and the Medication image is missing when clicked on here
![image](https://user-images.githubusercontent.com/939996/39881332-873ba77a-5478-11e8-82b6-f7cbc80e84c0.png)

**Comment by tony-shannon** [comment]
Update re
- [ ] A) Logout needs to work cleanly, need to check the issue there - @robtweed  working on it

**Comment by tony-shannon** [comment]
Added picture re BackButton issue

![image](https://user-images.githubusercontent.com/939996/39923089-1fbc2ece-551a-11e8-8d4d-88532feae504.png)

**Comment by olegmdev** [comment]
I'm working on task "C"

**Comment by tony-shannon** [comment]
Rob has worked on A) I will add it back to the tasks to be done on the PulseTile side

**Comment by tony-shannon** [comment]
re H

Kirill says the UI build resulting in a split of files is related to this work;
"Hi everyone, considering multiple javascript files, most likely this is due to chunking that has been done during the last weeks of March so each view does not load all of the javascript files"
"Code splitting or code chunking as its commonly called
Requesting code pieces on demand
"
https://github.com/PulseTile/PulseTile-React/commit/c6d85211b3868ada719975a51573dd7ae1e2e371

**Comment by tony-shannon** [comment]
when adding a new test patient, the Patient Summary/Meds pane is initially empty eeven though the data is there
on refresh  later the data appears

 
![image](https://user-images.githubusercontent.com/939996/40648374-379b5c44-6326-11e8-9170-1f9fbe025dff.png)

**Comment by PhilBarrett** [comment]
@olegmdev See images attached (medications and vaccinations) - licence /attribution free images - re Task "C". 
![medications 1](https://user-images.githubusercontent.com/12699244/40668118-9df8c1d6-635b-11e8-8364-4b45b34e698e.jpg)
![vaccinations 1](https://user-images.githubusercontent.com/12699244/40668122-9f481708-635b-11e8-9788-37fadf42c6b2.jpg)

**Comment by juliashulga** [comment]
@olegmdev  could you please move ahead with the task and use the images Phill sent above ?

**Comment by PhilBarrett** [comment]
UAT testing today, following issues encountered

- [ ] Creates and edits currently aren't storing (vaccinations, contacts etc etc)
- [ ] Feeds not up to date with latest dev work, didn't work
- [ ] received "Connection error  Cross-Origin Request Blocked: reading of remote resource is disallowed" - can this be replicated?
- [ ] Need to Add Helm Logo in and remove LCC logo, keeping NHS logo
- [ ] Need to add short medical description in plain language for detail view headers (currently says short blurb) @tony-shannon please can you suggest wording?

**Comment by robtweed** [comment]
Phil - I was able to add an Allergy record to H Booth and subsequently edit it.

I'm reluctant to add test records containing inappropriate values in order to test.  Do you have some proper, sensible test data examples I can try for each heading, so that if / when they work, I don't leave rubbish behind?

Can you provide more information on the 2nd and 3rd issues - ie steps I can go through to replicate the problem and see it for myself?

**Comment by juliashulga** [comment]
Hi @robtweed I tried to create new Allergie . 
- Sometimes it says "Current request is invalid." upon clicking on Complete button 
- "Julia's Cause" wasn't created but it didn't show any error upon saving the form > http://prntscr.com/jqzvoh  

Contacts : 
Form data > http://prntscr.com/jqzxjr
Error upon clicking Complete button > http://prntscr.com/jqzxnr

All other headings behave the same way
Can you please advise ?

**Comment by BogdanScherban** [comment]
@robtweed according to @tony-shannon task:
1) Display user friendly error messages when data is not being brought over.  (Server side message - needs info from QEWD)
2) Migrate feeds data from browser side to server side for all users in demo environment, so it is the default

Our proposition:

1) feeds request (/api/feeds) will return one additional parameter isActive which will be equal true or false, for example:
{
    name: 'BBC Health',
    landingPageUrl: 'http://www.bbc.co.uk/news/health',
    rssFeedUrl: 'http://feeds.bbci.co.uk/news/health/rss.xml?edition=uk#',
    sourceId: 'testSourceID1',
    isActive: true (or false)
}

2) When user checks any Feed, we will send API-request to update isActive parameter, something like:
/api/feeds/{sourseId}/status

**Comment by tony-shannon** [comment]
tthanks @BogdanScherban 
Please move that detailed technical comment to the issue that it relates to
either 
https://github.com/PulseTile/PulseTile-React/issues/128 if the work to be done is PulseTile side
or
https://github.com/RippleOSI/Ripple-Qewd/issues/85 if the work to be done is QEWDside
